// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetadataService exposes folder scan and metadata fix to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as takeout$0 from "../takeout/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExiftoolCheck reports whether ExifTool is available (PATH plus common install locations).
 * @returns {$CancellablePromise<$models.ExiftoolStatus>}
 */
export function ExiftoolCheck() {
    return $Call.ByID(2052937883).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * FixAbort stops the current fix after the current file finishes (or immediately if waiting on pause).
 * @returns {$CancellablePromise<void>}
 */
export function FixAbort() {
    return $Call.ByID(269939194);
}

/**
 * FixCheckpointAvailable reports whether a saved checkpoint exists for this folder (resume possible).
 * @param {string} folderPath
 * @returns {$CancellablePromise<boolean>}
 */
export function FixCheckpointAvailable(folderPath) {
    return $Call.ByID(587844845, folderPath);
}

/**
 * FixMetadata writes EXIF from sidecar JSON and optionally removes sidecar files.
 * If resume is true, completed paths from .takeout-md-fixer-checkpoint.json are skipped.
 * 
 * Work runs in a background goroutine so the Wails runtime can process other calls and events.
 * The UI should listen for "fix-progress" and a final "fix-complete" event (see FixComplete).
 * A non-nil error means the job could not be started (e.g. another fix is active).
 * @param {string} folderPath
 * @param {boolean} deleteJsonSidecars
 * @param {boolean} resume
 * @returns {$CancellablePromise<void>}
 */
export function FixMetadata(folderPath, deleteJsonSidecars, resume) {
    return $Call.ByID(682951661, folderPath, deleteJsonSidecars, resume);
}

/**
 * FixPause pauses the current fix between files.
 * @returns {$CancellablePromise<void>}
 */
export function FixPause() {
    return $Call.ByID(3356104986);
}

/**
 * FixResume continues a paused fix.
 * @returns {$CancellablePromise<void>}
 */
export function FixResume() {
    return $Call.ByID(3438800187);
}

/**
 * ScanFolder lists media files under folderPath and their JSON sidecars.
 * @param {string} folderPath
 * @returns {$CancellablePromise<takeout$0.ScanResult | null>}
 */
export function ScanFolder(folderPath) {
    return $Call.ByID(952712716, folderPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SelectFolder opens a native directory picker.
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(4044646341);
}

// Private type creation functions
const $$createType0 = $models.ExiftoolStatus.createFrom;
const $$createType1 = takeout$0.ScanResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
