// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetadataService exposes folder scan and metadata fix to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as takeout$0 from "../takeout/models.js";

/**
 * FixMetadata writes EXIF from sidecar JSON and optionally removes sidecar files.
 * @param {string} folderPath
 * @param {boolean} deleteJsonSidecars
 * @returns {$CancellablePromise<takeout$0.FixResult | null>}
 */
export function FixMetadata(folderPath, deleteJsonSidecars) {
    return $Call.ByID(682951661, folderPath, deleteJsonSidecars).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ScanFolder lists media files under folderPath and their JSON sidecars.
 * @param {string} folderPath
 * @returns {$CancellablePromise<takeout$0.ScanResult | null>}
 */
export function ScanFolder(folderPath) {
    return $Call.ByID(952712716, folderPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SelectFolder opens a native directory picker.
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(4044646341);
}

// Private type creation functions
const $$createType0 = takeout$0.FixResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = takeout$0.ScanResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
