// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExiftoolStatus is returned by ExiftoolCheck for the UI.
 */
export class ExiftoolStatus {
    /**
     * Creates a new ExiftoolStatus instance.
     * @param {Partial<ExiftoolStatus>} [$$source = {}] - The source object to create the ExiftoolStatus.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExiftoolStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExiftoolStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExiftoolStatus(/** @type {Partial<ExiftoolStatus>} */($$parsedSource));
    }
}
