// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class MediaFile {
    /**
     * Creates a new MediaFile instance.
     * @param {Partial<MediaFile>} [$$source = {}] - The source object to create the MediaFile.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("jsonPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jsonPath"] = "";
        }
        if (!("hasJson" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasJson"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MediaFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaFile(/** @type {Partial<MediaFile>} */($$parsedSource));
    }
}

export class ScanResult {
    /**
     * Creates a new ScanResult instance.
     * @param {Partial<ScanResult>} [$$source = {}] - The source object to create the ScanResult.
     */
    constructor($$source = {}) {
        if (!("folderPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderPath"] = "";
        }
        if (!("totalMedia" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalMedia"] = 0;
        }
        if (!("withJson" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["withJson"] = 0;
        }
        if (!("withoutJson" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["withoutJson"] = 0;
        }
        if (!("orphanJson" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["orphanJson"] = 0;
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {MediaFile[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField5_0($$parsedSource["files"]);
        }
        return new ScanResult(/** @type {Partial<ScanResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = MediaFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
