// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} folderPath
 * @param {boolean} deleteJsonSidecars
 * @returns {$CancellablePromise<$models.FixResult | null>}
 */
export function FixMetadata(folderPath, deleteJsonSidecars) {
    return $Call.ByID(2033193994, folderPath, deleteJsonSidecars).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} folderPath
 * @returns {$CancellablePromise<$models.ScanResult | null>}
 */
export function ScanFolder(folderPath) {
    return $Call.ByID(2768144357, folderPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(3581756672);
}

// Private type creation functions
const $$createType0 = $models.FixResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ScanResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
